image:
  - Visual Studio 2017
  - Ubuntu
init:
  - git config --global core.autocrlf input
install:
  - chmod +x build.sh
build_script:
  - cmd: build.cmd
  - sh: ./build.sh
test: off
version: 0.7.5.{build}
artifacts:
  - path: 'build\*.nupkg'
    name: NuGet