image:
  - Visual Studio 2017
  - Ubuntu
init:
  - git config --global core.autocrlf input
install:
  - dotnet tool install fake-cli -g
build_script:
  - fake build
test: off
version: 0.7.5.{build}
artifacts:
  - path: 'build\*.nupkg'
    name: NuGet